### ISSUE TITLE
dtabf.xsl : Problem, wenn Inhalte von <del> leeres Element enthält

### ISSUE THREAD

**Issue by cthomasdta** [haoess/dta-tools#21]
z. B. 
> `die innere<del rendition="#s" hand="#pencil"><metamark/></del> und<metamark/><add place="superlinear"> äußere</add> Erwärmung`

führt dazu, dass in der Stylesheet-Ansicht dann die folgende Passage insgesamt als gestrichen dargestellt wird. Im DTA siehts gut aus, siehe die oben zitierte Stelle http://www.deutschestextarchiv.de/nn_msgermqu2124_1827/21.

Könnte aber auch daran liegen, dass <metamark/> noch nicht umgesetzt wird, siehe nächstes issue.

**Comment by haoess** [comment]
fixed in 2ab742b4d0c87e491a7f985392b3104b10447825
